### ISSUE TITLE
Pravin Kumar Github Profile

### ISSUE THREAD

**Issue by pk0dev** [FrancescoXX/github-profile-review#11]
github.com/pravinkumarone

I'm an aspiring self taught DevOps Engineer

Worked in Non-IT for 4 years and decided to quit my job and start learning programming (what I wanted to do in the first place)

**Comment by FrancescoXX** [comment]
no badges or organizations
readme: add more images and stats
check [pravinkumar.one](https://pravinkumar.one/)
