### ISSUE TITLE
Review Github Profile

### ISSUE THREAD

**Issue by ABHIGYAN-MOHANTA** [FrancescoXX/github-profile-review#2]
https://github.com/ABHIGYAN-MOHANTA

**Comment by FrancescoXX** [comment]
done

**Comment by FrancescoXX** [comment]
too many labels
get some stars on pinned project
add redme on UnbreakableME app

**Comment by ABHIGYAN-MOHANTA** [comment]
Thanks, @FrancescoXX Really appreciate the feedback, I will work on this asap! Have a great stream and and great weekend!

**Comment by FrancescoXX** [comment]
https://www.youtube.com/live/r9_fkOn1SeY?si=Oi4FcAEo4sXKhu5H
