### ISSUE TITLE
Review github profile

### ISSUE THREAD

**Issue by Lalman888** [FrancescoXX/github-profile-review#24]
https://github.com/Lalman888

**Comment by FrancescoXX** [comment]
espress logo barley visible

**Comment by FrancescoXX** [comment]
only 2 repos pinned?
ghood visit india example
X account suspended https://twitter.com/LalmanThakur8
no profile picture
broken link http://lalmanthakur.co/

**Comment by Lalman888** [comment]
I have pushed my container image on docker hub then using docker-compose on azure web app I have deploy but it was stopped 

2023-11-02T17:43:31.929Z INFO - Container logs from dockergocomposeapp_go-app_0_e192a1f4 = 2023-11-02T17:43:27.437040941Z exec ./api: exec format error
2023-11-02T17:43:29.147376925Z exec ./api: exec format error
2023-11-02T17:43:30.887917295Z exec ./api: exec format error
<img width="1235" alt="Screenshot 2023-11-04 at 10 07 28 PM" src="https://github.com/FrancescoXX/github-profile-review/assets/90516185/1bcbf8e2-2cd8-4ea5-a3c1-b49026d351ec">

**Comment by Lalman888** [comment]
@FrancescoXX  and here is my portfolio I have fix the link http://lalmanthakur.co/
