### ISSUE TITLE
GitHub Profile Review

### ISSUE THREAD

**Issue by Mr-Destructive** [FrancescoXX/github-profile-review#25]
My handle: github.com/mr-destructive
Thank you @FrancescoXX  :+1:

**Comment by FrancescoXX** [comment]
no description https://github.com/Mr-Destructive/scifihub-app
good focus on golang
layout issues
![image](https://github.com/FrancescoXX/github-profile-review/assets/18360871/7ac2e886-1999-4945-877c-7e132a43c22c)
